"""blinds, start_money

Revision ID: 9f07662f73c1
Revises: abe09da1b3f4
Create Date: 2025-02-19 20:06:22.279343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f07662f73c1'
down_revision: Union[str, None] = 'abe09da1b3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('start_money', sa.Integer(), nullable=False))
    op.add_column('tables', sa.Column('big_blind', sa.Integer(), nullable=False))
    op.add_column('tables', sa.Column('small_blind', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'small_blind')
    op.drop_column('tables', 'big_blind')
    op.drop_column('tables', 'start_money')
    # ### end Alembic commands ###
