"""удалены defaul из Table (в start_money и big_blind)

Revision ID: eedca132d9ad
Revises: b666dea92164
Create Date: 2025-03-08 19:30:29.584699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eedca132d9ad'
down_revision: Union[str, None] = 'b666dea92164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
